# From https://conda.io/docs/travis.html
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # We could ad a conda reqs file with "--file
  - conda create -q -n test-environment python=3.6 numpy pandas pytest pytest-cov
  - which python
  - source activate test-environment
  - which python
  - python setup.py install

script:
  pytest -v --cov=pgm

after_success:
  - pip install codecov
  - codecov
